name = "primiti_ve/jecs_example"
version = "0.1.0"
repository = "https://github.com/Primiti-ve/jecs-example"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.1", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
Jecs = { name = "marked/jecs", version = "^0.9.0-rc.8" }
Planck = { wally = "yetanotherclown/planck", version = "^0.2.0" }
Jabby = { wally = "alicesaidhi/jabby", version = "^0.2.0" }
Planck_RunService = { wally = "yetanotherclown/planck-runservice", version = "^0.2.0" }
