name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs: 
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq


      - name: Get and Download Latest Pesde Linux Binary
        env:
          REPO: pesde-pkg/pesde
        run: |
          # Get latest release info from GitHub API
          RELEASE_JSON=$(curl -s "https://api.github.com/repos/$REPO/releases/latest")

          # Extract version tag
          VERSION=$(echo "$RELEASE_JSON" | jq -r .tag_name)

          # Find asset URL for linux-x86_64
          ASSET_URL=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | endswith("linux-x86_64.zip")) | .browser_download_url')

          if [ -z "$ASSET_URL" ]; then
            echo "Could not find a linux-x86_64.zip asset in release $VERSION"
            exit 1
          fi

          echo "Downloading: $ASSET_URL"
          curl -L "$ASSET_URL" -o pesde.zip
          unzip pesde.zip
          chmod +x pesde


      - name: Self-install Pesde
        run: |
          ./pesde self-install
          rm ./pesde
          echo "$HOME/.pesde/bin" >> $GITHUB_PATH

      - name: Add Pesde to PATH
        run: echo "$HOME/.pesde/bin" >> $GITHUB_PATH

      - name: Install Pesde Dependencies
        run: pesde install

      - name: Install Rojo
        run: |
          curl -L https://github.com/rojo-rbx/rojo/releases/latest/download/rojo-linux.zip -o rojo.zip
          unzip rojo.zip
          chmod +x rojo
          sudo mv rojo /usr/local/bin/rojo

      - name: Build jecs-example.rbxlx
        run: rojo build -o jecs-example.rbxlx pack.project.json

      - name: Upload jecs-example.rbxlx as build artifact
        uses: actions/upload-artifact@v4
        with: 
          name: jecs-example
          path: jecs-example.rbxlx

      - name: Get Version from pesde.toml
        uses: SebRollen/toml-action@v1.0.0
        id: read_toml
        with: 
          file: 'pesde.toml'
          field: 'version'

      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          name: ${{ steps.read_toml.outputs.value }}
          tag_name: ${{ steps.read_toml.outputs.value }}
          files: jecs-example.rbxlx
          draft: true
