name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs: 
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4

      - name: Get Latest Pesde Release Info
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: pesde-pkg/pesde

      - name: Download Pesde Linux Binary
        run: |
          LATEST_VERSION=${{ steps.latest_release.outputs.release }}
          ASSET_URL="https://github.com/pesde-pkg/pesde/releases/download/${LATEST_VERSION}/pesde-${LATEST_VERSION}-linux-x86_64.zip"
          curl -L "$ASSET_URL" -o pesde.zip
          unzip pesde.zip
          chmod +x pesde

      - name: Self-install Pesde
        run: |
          ./pesde self-install
          rm ./pesde
          echo "$HOME/.pesde/bin" >> $GITHUB_PATH

      - name: Add Pesde to PATH
        run: echo "$HOME/.pesde/bin" >> $GITHUB_PATH

      - name: Install Pesde Dependencies
        run: pesde install

      - name: Install Rojo
        run: |
          curl -L https://github.com/rojo-rbx/rojo/releases/latest/download/rojo-linux.zip -o rojo.zip
          unzip rojo.zip
          chmod +x rojo
          sudo mv rojo /usr/local/bin/rojo

      - name: Build jecs-example.rbxlx
        run: rojo build -o jecs-example.rbxlx pack.project.json

      - name: Upload jecs-example.rbxlx as build artifact
        uses: actions/upload-artifact@v4
        with: 
          name: jecs-example
          path: jecs-example.rbxlx

      - name: Get Version from pesde.toml
        uses: SebRollen/toml-action@v1.0.0
        id: read_toml
        with: 
          file: 'pesde.toml'
          field: 'version'

      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          name: ${{ steps.read_toml.outputs.value }}
          tag_name: ${{ steps.read_toml.outputs.value }}
          files: jecs-example.rbxlx
          draft: true
